FROM photon:3.0

MAINTAINER okurth@vmware.com

RUN tdnf update  -qy
RUN tdnf remove  -qy toybox
RUN tdnf install -qy --enablerepo=photon-debuginfo \
                       build-essential cmake curl-devel rpm-build libsolv-devel \
                       popt-devel sed createrepo_c glib libxml2 findutils \
                       python3 python3-setuptools python3-devel valgrind \
                       gpgme-devel glibc-debuginfo libxml2-devel \
                       openssl-devel zlib-devel which \
                       python3-requests python3-urllib3 python3-pyOpenSSL \
                       python3-pip

# TODO: we need to fix pytest in Ph3, after that this can be removed
RUN pip3 install -q pytest

CMD ["/bin/bash"]
