FROM fedora:34

RUN dnf -y upgrade
RUN dnf -y install gcc make cmake libcurl-devel rpm-devel rpm-build \
        libsolv-devel popt-devel sed createrepo_c glib2-devel libxml2 \
        findutils python3-pytest python3-requests python3-urllib3 \
        python3-pyOpenSSL python3 python3-devel valgrind gpgme-devel \
        libxml2-devel openssl-devel rpm-sign which python3-pip

RUN pip3 install flake8

CMD ["/bin/bash"]
