/*
 * Copyright (C) 2022 VMware, Inc. All Rights Reserved.
 *
 * Licensed under the GNU Lesser General Public License v2.1 (the "License");
 * you may not use this file except in compliance with the License. The terms
 * of the License are located in the COPYING file of this distribution.
 */

#ifndef __PLUGINS_METALINK_DEFINES_H
#define __PLUGINS_METALINK_DEFINES_H


#define ERROR_TDNF_METALINK_START 2700
#define ERROR_TDNF_METALINK_PARSER_INVALID_DOC_OBJECT       ERROR_TDNF_METALINK_START + 1
#define ERROR_TDNF_METALINK_PARSER_INVALID_ROOT_ELEMENT     ERROR_TDNF_METALINK_START + 2
#define ERROR_TDNF_METALINK_PARSER_MISSING_FILE_ATTR        ERROR_TDNF_METALINK_START + 3
#define ERROR_TDNF_METALINK_PARSER_INVALID_FILE_NAME        ERROR_TDNF_METALINK_START + 4
#define ERROR_TDNF_METALINK_PARSER_MISSING_FILE_SIZE        ERROR_TDNF_METALINK_START + 5
#define ERROR_TDNF_METALINK_PARSER_MISSING_HASH_ATTR        ERROR_TDNF_METALINK_START + 6
#define ERROR_TDNF_METALINK_PARSER_MISSING_HASH_CONTENT     ERROR_TDNF_METALINK_START + 7
#define ERROR_TDNF_METALINK_PARSER_MISSING_URL_ATTR         ERROR_TDNF_METALINK_START + 8
#define ERROR_TDNF_METALINK_PARSER_MISSING_URL_CONTENT      ERROR_TDNF_METALINK_START + 9
#define ERROR_TDNF_METALINK_END                             ERROR_TDNF_METALINK_START + 10

#define TDNF_REPO_CONFIG_METALINK_KEY "metalink"

#define METALINK_PLUGIN_ERROR "metalink plugin error"
#define METALINK_ERROR_TABLE \
{ \
    {ERROR_TDNF_METALINK_PARSER_INVALID_DOC_OBJECT,        "ERROR_TDNF_METALINK_PARSER_INVALID_DOC_OBJECT",        "Failed to parse and create document tree"},\
    {ERROR_TDNF_METALINK_PARSER_INVALID_ROOT_ELEMENT,      "ERROR_TDNF_METALINK_PARSER_INVALID_ROOT_ELEMENT",      "Root element not found"},\
    {ERROR_TDNF_METALINK_PARSER_MISSING_FILE_ATTR,         "ERROR_TDNF_METALINK_PARSER_MISSING_FILE_ATTR",         "Missing filename in metalink file"},\
    {ERROR_TDNF_METALINK_PARSER_INVALID_FILE_NAME,         "ERROR_TDNF_METALINK_PARSER_INVALID_FILE_NAME",         "Invalid filename present"},\
    {ERROR_TDNF_METALINK_PARSER_MISSING_FILE_SIZE,         "ERROR_TDNF_METALINK_PARSER_MISSING_FILE_SIZE",         "Missing file size in metalink file"},\
    {ERROR_TDNF_METALINK_PARSER_MISSING_HASH_ATTR,         "ERROR_TDNF_METALINK_PARSER_MISSING_HASH_ATTR",         "Missing attribute in hash tag"},\
    {ERROR_TDNF_METALINK_PARSER_MISSING_HASH_CONTENT,      "ERROR_TDNF_METALINK_PARSER_MISSING_HASH_CONTENT",      "Missing content in hash tag value"},\
    {ERROR_TDNF_METALINK_PARSER_MISSING_URL_ATTR,          "ERROR_TDNF_METALINK_PARSER_MISSING_URL_ATTR",          "Missing attribute in url tag"},\
    {ERROR_TDNF_METALINK_PARSER_MISSING_HASH_CONTENT,      "ERROR_TDNF_METALINK_PARSER_MISSING_URL_CONTENT",       "Missing content in url tag value"},\
};
#endif /* __PLUGINS_METALINK_DEFINES_H__ */
